language: python
python:
    - "2.7"

# Cache PlatformIO packages using Travis CI container-based infrastructure
sudo: false
cache:
    directories:
        - "~/.platformio"

env:
    - PLATFORMIO_CI_SRC=examples/3DCube


install:
    - pip install -U platformio
    #- platformio lib install "JsonStreamingParser" "WifiManager" "simpleDSTadjust" "DHT sensor library"
    - platformio lib update

script:
    - platformio ci --lib="." --board=nodemcuv2
Contact GitHub API Training Shop Blog About
